#include "web_page.h"

const char ROBOT_CONTROL_PAGE[] =
    "<!doctype html><html lang=\"en\"><head>"
    "<meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1,viewport-fit=cover\">"
    "<title>Robot Control</title><style>"
    ":root{color-scheme:light;font-family:Inter,system-ui,sans-serif;background:#f3f5f7;color:#17202a}"
    "*{box-sizing:border-box}body{margin:0;min-height:100vh;background:#f3f5f7}"
    "header{height:58px;background:#17202a;color:#fff;display:flex;align-items:center;justify-content:space-between;padding:0 20px}"
    "h1{font-size:18px;margin:0;font-weight:700;letter-spacing:0}.connection{display:flex;align-items:center;gap:8px;font-size:13px}"
    ".dot{width:9px;height:9px;border-radius:50%;background:#d04444}.dot.online{background:#35a56f}"
    "main{width:min(620px,100%);margin:0 auto;padding:20px 16px 32px}"
    ".estop-banner{display:none;background:#a6252b;color:#fff;padding:12px 14px;margin-bottom:16px;border-radius:6px;font-weight:800;text-align:center}"
    ".estop-banner.active{display:block}.section{padding:18px 0;border-bottom:1px solid #d6dce1}"
    ".section:first-of-type{padding-top:0}.section-title{font-size:13px;text-transform:uppercase;color:#58636d;font-weight:700;margin:0 0 14px}"
    ".drive-grid{display:grid;grid-template-columns:repeat(3,74px);grid-template-rows:repeat(3,64px);gap:10px;justify-content:center}"
    "button{font:inherit;border:0;border-radius:6px;cursor:pointer;touch-action:none;user-select:none;transition:background .12s,transform .08s}"
    "button:active{transform:translateY(1px)}button:disabled{cursor:not-allowed;opacity:.42}"
    ".drive{background:#fff;border:1px solid #bac3cb;color:#17202a;font-size:25px;font-weight:700;box-shadow:0 1px 2px #00000012}"
    ".drive.active{background:#d8e8f4;border-color:#31769f}.forward{grid-column:2}.left{grid-column:1;grid-row:2}.stop{grid-column:2;grid-row:2;background:#313b44;color:#fff;font-size:13px;font-weight:800}.right{grid-column:3;grid-row:2}.backward{grid-column:2;grid-row:3}"
    ".speed-row{display:grid;grid-template-columns:auto 1fr 54px;align-items:center;gap:12px;margin-top:18px;font-size:14px}"
    "input[type=range]{width:100%;accent-color:#31769f}.speed-value{text-align:right;font-variant-numeric:tabular-nums;font-weight:700}"
    ".servo-grid{display:grid;gap:14px}.servo-row{display:grid;grid-template-columns:46px 1fr 48px;align-items:center;gap:12px;font-size:14px}.servo-value{text-align:right;font-variant-numeric:tabular-nums;font-weight:700}"
    ".expression-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.expression{min-height:40px;background:#fff;border:1px solid #bac3cb;color:#28343e;font-size:13px;font-weight:650}.expression.active{background:#d8e8f4;border-color:#31769f;color:#205a7b}"
    ".tts-actions{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.tts-button{min-height:42px;background:#fff;border:1px solid #bac3cb;color:#28343e;font-size:14px;font-weight:650}"
    ".safety-actions{display:grid;grid-template-columns:1fr 1fr;gap:10px}.estop{min-height:52px;background:#c52d35;color:#fff;font-weight:800}.clear{min-height:52px;background:#fff;color:#8c2026;border:1px solid #c52d35;font-weight:700}"
    ".status-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px 18px;font-size:13px}.metric{display:flex;justify-content:space-between;gap:8px}.metric span:first-child{color:#68737d}.metric span:last-child{font-weight:650;text-align:right}"
    "@media(max-width:390px){main{padding-inline:12px}.drive-grid{grid-template-columns:repeat(3,68px)}.expression-grid,.tts-actions{grid-template-columns:repeat(2,1fr)}.safety-actions{grid-template-columns:1fr}.status-grid{grid-template-columns:1fr}}"
    "</style></head><body><header><h1>Robot Control</h1><div class=\"connection\"><span id=\"dot\" class=\"dot\"></span><span id=\"connection\">Connecting</span></div></header>"
    "<main><div id=\"estopBanner\" class=\"estop-banner\">EMERGENCY STOP ACTIVE</div>"
    "<section class=\"section\"><p class=\"section-title\">Drive</p><div class=\"drive-grid\">"
    "<button class=\"drive forward\" data-command=\"forward\" aria-label=\"Forward\">&#8593;</button>"
    "<button class=\"drive left\" data-command=\"left\" aria-label=\"Turn left\">&#8592;</button>"
    "<button id=\"stop\" class=\"stop\">STOP</button>"
    "<button class=\"drive right\" data-command=\"right\" aria-label=\"Turn right\">&#8594;</button>"
    "<button class=\"drive backward\" data-command=\"backward\" aria-label=\"Backward\">&#8595;</button>"
    "</div><div class=\"speed-row\"><label for=\"speed\">Speed</label><input id=\"speed\" type=\"range\" min=\"0\" max=\"100\" value=\"40\"><span id=\"speedValue\" class=\"speed-value\">40%</span></div></section>"
    "<section class=\"section\"><p class=\"section-title\">Gimbal</p><div class=\"servo-grid\">"
    "<div class=\"servo-row\"><label for=\"yaw\">Yaw</label><input id=\"yaw\" type=\"range\" min=\"45\" max=\"135\" value=\"90\"><span id=\"yawValue\" class=\"servo-value\">90&deg;</span></div>"
    "<div class=\"servo-row\"><label for=\"pitch\">Pitch</label><input id=\"pitch\" type=\"range\" min=\"60\" max=\"120\" value=\"90\"><span id=\"pitchValue\" class=\"servo-value\">90&deg;</span></div>"
    "</div></section>"
    "<section class=\"section\"><p class=\"section-title\">Expression</p><div class=\"expression-grid\">"
    "<button class=\"expression active\" data-expression=\"idle\">Idle</button><button class=\"expression\" data-expression=\"happy\">Happy</button>"
    "<button class=\"expression\" data-expression=\"curious\">Curious</button><button class=\"expression\" data-expression=\"confused\">Confused</button>"
    "<button class=\"expression\" data-expression=\"sleepy\">Sleepy</button><button class=\"expression\" data-expression=\"watching\">Watching</button>"
    "<button class=\"expression\" data-expression=\"warning\">Warning</button><button class=\"expression\" data-expression=\"excited\">Excited</button>"
    "</div></section>"
    "<section class=\"section\"><p class=\"section-title\">Voice</p><div class=\"tts-actions\">"
    "<button class=\"tts-button\" data-phrase=\"hello\">&#20320;&#22909;</button><button class=\"tts-button\" data-phrase=\"here\">&#25105;&#22312;&#36825;&#37324;</button>"
    "<button class=\"tts-button\" data-phrase=\"received\">&#25910;&#21040;</button><button class=\"tts-button\" data-phrase=\"stopped\">&#20572;&#19979;&#26469;&#20102;</button>"
    "</div></section>"
    "<section class=\"section\"><p class=\"section-title\">Safety</p><div class=\"safety-actions\"><button id=\"estop\" class=\"estop\">EMERGENCY STOP</button><button id=\"clear\" class=\"clear\" disabled>CLEAR E-STOP</button></div></section>"
    "<section class=\"section\"><p class=\"section-title\">Status</p><div class=\"status-grid\">"
    "<div class=\"metric\"><span>IP</span><span id=\"ip\">--</span></div><div class=\"metric\"><span>RSSI</span><span id=\"rssi\">--</span></div>"
    "<div class=\"metric\"><span>Motion</span><span id=\"motion\">STOP</span></div><div class=\"metric\"><span>Watchdog</span><span id=\"watchdog\">Idle</span></div>"
    "<div class=\"metric\"><span>Reconnects</span><span id=\"reconnects\">0</span></div><div class=\"metric\"><span>Last stop</span><span id=\"lastStop\">BOOT</span></div>"
    "<div class=\"metric\"><span>Expression</span><span id=\"expressionStatus\">Idle</span></div>"
    "<div class=\"metric\"><span>Last voice</span><span id=\"ttsStatus\">--</span></div>"
    "</div></section></main><script>"
    "const driveButtons=[...document.querySelectorAll('[data-command]')],expressionButtons=[...document.querySelectorAll('[data-expression]')],ttsButtons=[...document.querySelectorAll('[data-phrase]')],speed=document.getElementById('speed'),speedValue=document.getElementById('speedValue'),yaw=document.getElementById('yaw'),pitch=document.getElementById('pitch'),yawValue=document.getElementById('yawValue'),pitchValue=document.getElementById('pitchValue');"
    "let estop=false,online=false,oledReady=false,ttsReady=false,activeCommand=null,activeKey=null,holdTimer=null,driveInFlight=false;"
    "let yawTimer=null,pitchTimer=null;"
    "const PITCH_THROTTLE_MS=40;"
    "const keyMap={KeyW:'forward',ArrowUp:'forward',KeyS:'backward',ArrowDown:'backward',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right'};"
    "async function post(path){const response=await fetch(path,{method:'POST',cache:'no-store'});let data={};try{data=await response.json()}catch{}if(!response.ok)throw Object.assign(new Error(data.error||response.statusText),{status:response.status});return data}"
    "function driveUrl(command){return '/api/drive?command='+command+'&speed='+speed.value}"
    "function markActive(command){driveButtons.forEach(button=>button.classList.toggle('active',button.dataset.command===command))}"
    "function stopRepeating(){if(holdTimer!==null)clearInterval(holdTimer);holdTimer=null;activeCommand=null;markActive(null)}"
    "async function stopDrive(){stopRepeating();try{await post('/api/stop')}catch{}setTimeout(()=>post('/api/stop').catch(()=>{}),100)}"
    "function sendActiveDrive(){if(!activeCommand||driveInFlight)return;driveInFlight=true;post(driveUrl(activeCommand)).catch(handleDriveError).finally(()=>{driveInFlight=false})}"
    "function startDrive(command){if(estop||!online)return;stopRepeating();activeCommand=command;markActive(command);sendActiveDrive();holdTimer=setInterval(sendActiveDrive,200)}"
    "function handleDriveError(error){if(error.status===409){estop=true;renderLock()}stopRepeating()}"
    "function renderLock(){document.getElementById('estopBanner').classList.toggle('active',estop);document.getElementById('clear').disabled=!estop;driveButtons.forEach(button=>button.disabled=estop||!online);expressionButtons.forEach(button=>button.disabled=!online||!oledReady);ttsButtons.forEach(button=>button.disabled=!online||!ttsReady);yaw.disabled=!online;pitch.disabled=!online}"
    "function setServoDisplay(input,label,value,min,max){input.min=min;input.max=max;if(document.activeElement!==input)input.value=value;label.textContent=input.value+'\u00b0'}"
    "function renderExpression(expression){expressionButtons.forEach(button=>button.classList.toggle('active',button.dataset.expression===expression));document.getElementById('expressionStatus').textContent=expression}"
    "async function refresh(){try{const response=await fetch('/status',{cache:'no-store'});if(!response.ok)throw new Error();const data=await response.json();online=!!data.wifi_connected;oledReady=!!data.oled_ready;ttsReady=!!data.tts_ready;estop=!!data.estop;document.getElementById('dot').classList.toggle('online',online);document.getElementById('connection').textContent=online?'Online':'Offline';document.getElementById('ip').textContent=data.ip;document.getElementById('rssi').textContent=data.rssi===null?'--':data.rssi+' dBm';document.getElementById('motion').textContent=data.motion+' '+data.speed+'%';document.getElementById('watchdog').textContent=data.watchdog_armed?'Armed':'Idle';document.getElementById('reconnects').textContent=data.wifi_reconnects;document.getElementById('lastStop').textContent=data.last_stop_reason;document.getElementById('ttsStatus').textContent=data.tts_last_phrase||'--';setServoDisplay(yaw,yawValue,data.yaw,data.yaw_min,data.yaw_max);setServoDisplay(pitch,pitchValue,data.pitch,data.pitch_min,data.pitch_max);renderExpression(data.expression);renderLock()}catch{online=false;oledReady=false;ttsReady=false;document.getElementById('dot').classList.remove('online');document.getElementById('connection').textContent='Offline';renderLock()}}"
    "driveButtons.forEach(button=>button.addEventListener('pointerdown',event=>{event.preventDefault();button.setPointerCapture(event.pointerId);startDrive(button.dataset.command)}));"
    "window.addEventListener('pointerup',()=>{if(activeCommand)stopDrive()});window.addEventListener('pointercancel',()=>{if(activeCommand)stopDrive()});"
    "document.getElementById('stop').addEventListener('click',stopDrive);"
    "document.getElementById('estop').addEventListener('click',async()=>{stopRepeating();try{await post('/api/estop')}finally{estop=true;renderLock();refresh()}});"
    "document.getElementById('clear').addEventListener('click',async()=>{try{await post('/api/estop/clear');estop=false;renderLock();refresh()}catch{}});"
    "speed.addEventListener('input',()=>{speedValue.textContent=speed.value+'%';sendActiveDrive()});"
    "function scheduleYaw(){yawValue.textContent=yaw.value+'\u00b0';if(yawTimer!==null)clearTimeout(yawTimer);yawTimer=setTimeout(()=>{yawTimer=null;post('/api/servo?axis=yaw&angle='+yaw.value).catch(()=>refresh())},60)}"
    "function schedulePitch(){pitchValue.textContent=pitch.value+'\u00b0';if(pitchTimer!==null)return;pitchTimer=setTimeout(()=>{pitchTimer=null;post('/api/servo?axis=pitch&angle='+pitch.value).catch(()=>refresh())},PITCH_THROTTLE_MS)}"
    "yaw.addEventListener('input',scheduleYaw);pitch.addEventListener('input',schedulePitch);"
    "expressionButtons.forEach(button=>button.addEventListener('click',async()=>{try{await post('/api/oled?expression='+button.dataset.expression);renderExpression(button.dataset.expression)}catch{refresh()}}));"
    "ttsButtons.forEach(button=>button.addEventListener('click',async()=>{try{await post('/api/tts?phrase='+button.dataset.phrase);document.getElementById('ttsStatus').textContent=button.dataset.phrase}catch{refresh()}}));"
    "window.addEventListener('keydown',event=>{if(event.code==='Space'){event.preventDefault();activeKey=null;stopDrive();return}const command=keyMap[event.code];if(!command||event.repeat)return;event.preventDefault();activeKey=event.code;startDrive(command)});"
    "window.addEventListener('keyup',event=>{if(event.code===activeKey){event.preventDefault();activeKey=null;stopDrive()}});"
    "function emergencyRelease(){stopRepeating();navigator.sendBeacon('/api/stop')}window.addEventListener('blur',emergencyRelease);window.addEventListener('pagehide',emergencyRelease);document.addEventListener('visibilitychange',()=>{if(document.hidden)emergencyRelease()});"
    "refresh();setInterval(refresh,1000);"
    "</script></body></html>";

const size_t ROBOT_CONTROL_PAGE_LENGTH = sizeof(ROBOT_CONTROL_PAGE) - 1U;
